import { questions, classify, applicableQuestions, typeDefinitions } from '../server/catalog.js'

const json = (data, status=200) => new Response(JSON.stringify(data), { status, headers:{'content-type':'application/json; charset=utf-8'} })
const body = async req => { try { return await req.json() } catch { return {} } }
const rows = async stmt => (await stmt.all()).results
const one = async stmt => (await stmt.first()) || null
const bearer = req => (req.headers.get('authorization')||'').replace(/^Bearer\s+/,'')

async function seed(db) {
  const count = await one(db.prepare('SELECT count(*) n FROM stretch_types'))
  if (!count?.n) for (const t of typeDefinitions) await db.prepare('INSERT OR IGNORE INTO stretch_types(slug,name,body_part,description) VALUES(?,?,?,?)').bind(...t).run()
  const sc = await one(db.prepare('SELECT count(*) n FROM stretches'))
  if (!sc?.n) {
    for(let i=0;i<30;i++){const n=String(i+1).padStart(2,'0'),part=['首','肩','背中','腰・お尻','股関節','脚'][i%6];await db.prepare('INSERT INTO stretches(name,body_part,tags,video_url,duration_seconds,priority) VALUES(?,?,?,?,?,?)').bind(`Sample Stretch ${n}`,part,JSON.stringify(['サンプル',part]),`https://www.youtube.com/results?search_query=Sample+Stretch+${n}`,30+(i%2)*15,i+1).run()}
    const ts=await rows(db.prepare('SELECT id FROM stretch_types ORDER BY id')), ss=await rows(db.prepare('SELECT id FROM stretches ORDER BY id'))
    for(let i=0;i<ts.length;i++)for(let p=0;p<3;p++)await db.prepare('INSERT OR IGNORE INTO stretch_type_stretches VALUES(?,?,?)').bind(ts[i].id,ss[(i*3+p)%ss.length].id,p+1).run()
  }
}

async function menu(db,typeId){
  let result=await rows(db.prepare('SELECT s.* FROM stretches s JOIN stretch_type_stretches x ON x.stretch_id=s.id WHERE x.stretch_type_id=? AND s.published=1 ORDER BY x.position,s.priority LIMIT 5').bind(typeId))
  if(result.length<3){const fill=await rows(db.prepare(`SELECT * FROM stretches WHERE published=1 AND id NOT IN (${result.map(()=>'?').join(',')||'NULL'}) ORDER BY priority,id LIMIT ?`).bind(...result.map(x=>x.id),3-result.length));result=[...result,...fill]}
  return result
}
async function resultFor(db,id){const assessment=await one(db.prepare('SELECT a.*,t.name type_name,t.description FROM assessments a LEFT JOIN stretch_types t ON t.id=a.stretch_type_id WHERE a.id=?').bind(id));return {assessment,menu:assessment?.stretch_type_id?await menu(db,assessment.stretch_type_id):[]}}

async function lineSignature(raw,signature,secret){if(!secret||!signature)return false;const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const mac=await crypto.subtle.sign('HMAC',key,raw);const expected=btoa(String.fromCharCode(...new Uint8Array(mac)));return expected===signature}
async function pushLine(env,to,messages){const r=await fetch('https://api.line.me/v2/bot/message/push',{method:'POST',headers:{authorization:`Bearer ${env.LINE_CHANNEL_ACCESS_TOKEN}`,'content-type':'application/json'},body:JSON.stringify({to,messages})});if(!r.ok)throw new Error(`LINE push failed: ${r.status}`)}

async function api(req,env,url){
  const db=env.DB, p=url.pathname, method=req.method; await seed(db)
  if(p==='/api/config'&&method==='GET')return json({liffId:env.LIFF_ID||'',questions})
  if(p==='/api/health'&&method==='GET'){await db.prepare('SELECT 1').first();return json({status:'ok',database:'ok',time:new Date().toISOString()})}
  if(p==='/api/assessments/start'&&method==='POST'){const x=await body(req),ip=req.headers.get('cf-connecting-ip')||crypto.randomUUID(),lineId=String(x.lineUserId||`guest-${ip}`).slice(0,200);await db.prepare('INSERT INTO users(line_user_id) VALUES(?) ON CONFLICT(line_user_id) DO UPDATE SET last_used_at=CURRENT_TIMESTAMP').bind(lineId).run();let u=await one(db.prepare('SELECT * FROM users WHERE line_user_id=?').bind(lineId));if(x.consent){await db.prepare('UPDATE users SET consent_at=COALESCE(consent_at,CURRENT_TIMESTAMP) WHERE id=?').bind(u.id).run();u=await one(db.prepare('SELECT * FROM users WHERE id=?').bind(u.id))}if(!u.consent_at)return json({message:'内容をご確認のうえ、同意してから始めてください。'},400);let d=await one(db.prepare("SELECT id FROM assessments WHERE user_id=? AND status='in_progress' ORDER BY id DESC LIMIT 1").bind(u.id));if(!d){const r=await db.prepare('INSERT INTO assessments(user_id) VALUES(?)').bind(u.id).run();d={id:r.meta.last_row_id}}const ans=await rows(db.prepare('SELECT question_id,answer FROM assessment_answers WHERE assessment_id=?').bind(d.id));return json({assessmentId:d.id,answers:Object.fromEntries(ans.map(a=>[a.question_id,a.answer]))})}
  let m=p.match(/^\/api\/assessments\/(\d+)\/answer$/);if(m&&method==='PUT'){const x=await body(req);if(!x.questionId||!x.answer)return json({message:'回答を選んでください。'},400);await db.prepare('INSERT INTO assessment_answers VALUES(?,?,?) ON CONFLICT(assessment_id,question_id) DO UPDATE SET answer=excluded.answer').bind(m[1],x.questionId,x.answer).run();return json({ok:true})}
  m=p.match(/^\/api\/assessments\/(\d+)\/complete$/);if(m&&method==='POST'){const a=await one(db.prepare('SELECT * FROM assessments WHERE id=?').bind(m[1]));if(!a)return json({message:'チェックが見つかりません。'},404);if(a.status==='completed'||a.status==='excluded')return json(await resultFor(db,a.id));const ar=await rows(db.prepare('SELECT question_id,answer FROM assessment_answers WHERE assessment_id=?').bind(a.id)),answers=Object.fromEntries(ar.map(x=>[x.question_id,x.answer]));if(applicableQuestions(answers).some(q=>!answers[q.id]))return json({message:'未回答の質問があります。'},400);const out=classify(answers),t=out.unsafe?null:await one(db.prepare('SELECT id FROM stretch_types WHERE slug=? AND active=1').bind(out.slug));if(!out.unsafe&&!t)return json({message:'メニューを準備中です。'},422);await db.prepare('UPDATE assessments SET status=?,main_body_part=?,stretch_type_id=?,is_unsafe=?,excluded_reason=?,completed_at=CURRENT_TIMESTAMP WHERE id=?').bind(out.unsafe?'excluded':'completed',answers.body_part,t?.id||null,out.unsafe?1:0,out.reason||null,a.id).run();await db.prepare("INSERT OR IGNORE INTO activity_logs(user_id,assessment_id,event_type,event_key) VALUES(?,?,'assessment_completed',?)").bind(a.user_id,a.id,`complete-${a.id}`).run();await db.prepare("UPDATE followup_outbox SET status='canceled',canceled_at=CURRENT_TIMESTAMP WHERE user_id=? AND status='pending'").bind(a.user_id).run();if(!out.unsafe)for(const [kind,days] of [['day1',1],['day3',3],['day7',7]])await db.prepare("INSERT OR IGNORE INTO followup_outbox(user_id,assessment_id,kind,due_at,scheduled_at,idempotency_key) VALUES(?,?,?,datetime('now',?),datetime('now',?),?)").bind(a.user_id,a.id,kind,`+${days} day`,`+${days} day`,`${a.id}-${kind}`).run();return json(await resultFor(db,a.id))}
  m=p.match(/^\/api\/assessments\/(\d+)$/);if(m&&method==='GET')return json(await resultFor(db,m[1]))
  if(p==='/api/activity'&&method==='POST'){const x=await body(req),a=await one(db.prepare('SELECT * FROM assessments WHERE id=?').bind(x.assessmentId));if(!a)return json({message:'チェックが見つかりません。'},404);const key=x.eventKey||`${x.eventType}-${a.id}-${x.stretchId||'all'}-${new Date().toISOString().slice(0,10)}`;await db.prepare('INSERT OR IGNORE INTO activity_logs(user_id,assessment_id,stretch_id,event_type,event_key) VALUES(?,?,?,?,?)').bind(a.user_id,a.id,x.stretchId||null,x.eventType,key).run();return json({ok:true})}
  m=p.match(/^\/api\/assessments\/(\d+)\/seven-day$/);if(m&&method==='POST'){const x=await body(req),allowed=['かなり楽','少し楽','変わらない','悪化した'];if(!allowed.includes(x.result))return json({message:'選択肢から回答してください。'},400);await db.prepare('UPDATE assessments SET seven_day_result=? WHERE id=?').bind(x.result,m[1]).run();return json({action:x.result==='悪化した'?'safety':x.result==='変わらない'?'recheck':'continue'})}
  if(p==='/api/admin/dashboard'&&method==='GET'){if(bearer(req)!==env.ADMIN_TOKEN)return json({message:'管理者認証が必要です。'},401);return json({funnel:await one(db.prepare("SELECT count(DISTINCT CASE WHEN event_type='assessment_completed' THEN assessment_id END) completed,count(DISTINCT CASE WHEN event_type='video_click' THEN assessment_id END) video_clicks,count(DISTINCT CASE WHEN event_type='completed_stretch' THEN assessment_id END) exercised FROM activity_logs")),users:(await one(db.prepare('SELECT count(*) total FROM users'))).total,quality:await one(db.prepare("SELECT count(*) assessments,sum(is_unsafe) excluded,round(100.0*sum(is_unsafe)/max(count(*),1),1) excluded_rate FROM assessments")),types:await rows(db.prepare('SELECT t.name,count(a.id) count FROM stretch_types t LEFT JOIN assessments a ON a.stretch_type_id=t.id GROUP BY t.id ORDER BY count DESC')),recent:await rows(db.prepare('SELECT a.id,a.main_body_part,t.name type_name,a.completed_at,a.is_unsafe FROM assessments a LEFT JOIN stretch_types t ON t.id=a.stretch_type_id ORDER BY a.id DESC LIMIT 30'))})}
  if(p==='/api/admin/stretches'&&method==='GET'){if(bearer(req)!==env.ADMIN_TOKEN)return json({message:'管理者認証が必要です。'},401);return json(await rows(db.prepare('SELECT * FROM stretches ORDER BY priority,id')))}
  if(p==='/api/admin/types'&&method==='GET'){if(bearer(req)!==env.ADMIN_TOKEN)return json({message:'管理者認証が必要です。'},401);return json(await rows(db.prepare('SELECT t.*,sum(CASE WHEN s.published=1 THEN 1 ELSE 0 END) published_stretches FROM stretch_types t LEFT JOIN stretch_type_stretches x ON x.stretch_type_id=t.id LEFT JOIN stretches s ON s.id=x.stretch_id GROUP BY t.id ORDER BY t.body_part,t.name')))}
  if(p==='/api/line/webhook'&&method==='POST'){const raw=await req.clone().arrayBuffer();if(!await lineSignature(raw,req.headers.get('x-line-signature'),env.LINE_CHANNEL_SECRET))return new Response(null,{status:401});const x=await req.json();for(const e of x.events||[])if(e.type==='postback'){const q=new URLSearchParams(e.postback.data),a=await one(db.prepare('SELECT * FROM assessments WHERE id=?').bind(q.get('assessment_id')));if(a)await db.prepare('INSERT OR IGNORE INTO activity_logs(user_id,assessment_id,event_type,event_key) VALUES(?,?,?,?)').bind(a.user_id,a.id,`followup_${q.get('action')}`,`postback-${e.replyToken}`).run();if(['stop','worse','pain'].includes(q.get('action'))&&a)await db.prepare("UPDATE followup_outbox SET status='canceled',canceled_at=CURRENT_TIMESTAMP WHERE user_id=? AND status='pending'").bind(a.user_id).run()}return json({ok:true})}
  if(p==='/api/jobs/followups'&&method==='POST'){if(bearer(req)!==env.CRON_SECRET)return new Response(null,{status:401});return json(await followups(env))}
  return json({message:'ページが見つかりません。'},404)
}

async function followups(env){const hour=Number(new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',hour:'2-digit',hour12:false}).format(new Date()));if(hour<9||hour>=21)return {processed:0,deferred:true};const jobs=await rows(env.DB.prepare("SELECT o.*,u.line_user_id FROM followup_outbox o JOIN users u ON u.id=o.user_id WHERE o.status='pending' AND o.canceled_at IS NULL AND u.blocked_at IS NULL AND o.due_at<=datetime('now') LIMIT 100"));for(const j of jobs){const choices=j.kind==='day1'?[['やった','done'],['まだ','not_yet'],['合わなかった','not_fit']]:j.kind==='day3'?[['ラクになった','better'],['変わらない','same'],['つらい','worse']]:[['もう一度チェック','recheck'],['別の部位もみる','other'],['続けるコツ','continue']],text=j.kind==='day1'?'昨日の3本、1本でも試せましたか？':j.kind==='day3'?'この3日で、体の感じはどうですか？':'1週間おつかれさまでした。';const actions=choices.map(([label,action])=>({type:'postback',label,data:`action=${action}&assessment_id=${j.assessment_id}&step=${j.kind}`}));actions.push({type:'postback',label:'通知を止める',data:`action=stop&assessment_id=${j.assessment_id}&step=${j.kind}`});try{await pushLine(env,j.line_user_id,[{type:'template',altText:text,template:{type:'buttons',text,actions}}]);await env.DB.prepare("UPDATE followup_outbox SET status='sent',sent_at=CURRENT_TIMESTAMP,attempts=attempts+1 WHERE id=?").bind(j.id).run()}catch(e){await env.DB.prepare('UPDATE followup_outbox SET attempts=attempts+1,last_error=? WHERE id=?').bind(String(e.message),j.id).run()}}return {processed:jobs.length}}

export default {async fetch(req,env){try{const url=new URL(req.url);if(url.pathname.startsWith('/api/'))return await api(req,env,url);return env.ASSETS.fetch(req)}catch(e){console.error(e);return json({message:'うまく保存できませんでした。少し待ってもう一度お試しください。'},500)}},async scheduled(_event,env){await followups(env)}}
